### ISSUE TITLE
vertauschte Wörter Plugin vertauscht keine Wörter

### ISSUE THREAD

**Issue by MCsharerGIT** [asozialesnetzwerk/VertauschteWoerterPlugin#13]
Ich mochte das Plugin immer sehr und habe es sehr gerne und häufig benutzt und baue wieder viel zu lange und unnötige Schachtelsätze für diesen Report weshalb das jetzt leider viel schwieriger und aufwändiger zum lesen wird und das tut mir auch sehr leid, dass ich keine Kommas benutze bis auf das eine da gerade eben und ich fange jetzt mal an zu beschreiben warum ich eigentlich schreibe, denn das wäre glaube ich mal ganz gut.

**Seit einiger Zeit vertauscht das Plugin (ich benutze es mit Firefox 100.0.2 (64 Bit)) keine Wörter mehr. Vorher funktionierte es tadellos.**

So das wars dann auch schon jetzt schreibe ich noch mehr sinnlose Sachen damit es nerviger wird es sich durchzulesen aber man kann alles was nicht fett ist in diesem Report auch ignorieren. Trotzdem gibt es hier noch mehr Text, damit der Report nicht so leer wirkt und man noch ein bisschen zu lesen hat. Da fällt mir gerade auf, dass die Zeit vielleicht besser genutzt wäre den Fehler zu beheben deshalb höre ich jetzt mal lieber auf, schließlich hat nicht jeder unendlich viel Zeit sondern muss die Känguru-Chroniken/Manifest/Offenbarung usw. hören bzw. lesen.
Noch guten Appetit zum nächsten Mittag und viele Grüße.
Ein Nutzer.

Hier noch ein falsch zugeordnetes Zitat:
> „Wer einen Fehler gemacht hat und nicht korrigiert, begeht einen zweiten.“ (Joshix)

**Comment by Joshix-1** [comment]
Du hast im ersten Absatz zwei Kommata verwendet.

Soll mir das falsche Zitat unterschwellig sagen, dass ich den Fehler beheben soll?

**Comment by Joshix-1** [comment]
fixed in 3.1.3, danke für den Hinweis :)
