### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by j340m3** [asozialesnetzwerk/VertauschteWoerterPlugin#2]
Is it possible to incorporate case insensitivity? The plugin works for me only when I add also the Nouns with first uppercase latter.

**Comment by Joshix-1** [comment]
Weird. The code looks like it should work case insensitive.

**Comment by j340m3** [comment]
For more context, I use

- Browser: Brave Version 1.20.103 Chromium: 88.0.4324.152 (Offizieller Build) unknown (64-Bit) 
- OS: Linux 5.10.12-1-ck #1 SMP PREEMPT Sun, 31 Jan 2021 14:48:54 +0000 x86_64 GNU/Linux

**Comment by j340m3** [comment]
Nevermind, I was stupid. It works case insensitive.

**Comment by Joshix-1** [comment]
What was the problem?

**Comment by j340m3** [comment]
I forgot to hit save *facepalm*
