### ISSUE TITLE
Spaces being swallowed

### ISSUE THREAD

**Issue by j340m3** [asozialesnetzwerk/VertauschteWoerterPlugin#3]
When I try to read an Wikipedia-Article (for ex. https://de.wikipedia.org/wiki/Arbeitnehmer), severeal spaces between Words get lost.

**Comment by Joshix-1** [comment]
i'll look into this

**Comment by Joshix-1** [comment]
https://github.com/asozialesnetzwerk/VertauschteWoerterPlugin/commit/1a5e3b91d337dc4553ea855477562fce82dc68cf should fix this.
